name: CI GaragePhp

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Configuration PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3" #la version de PHP que vous utilisez, voir compatibilité avec version 8.4
          extensions: pdo_mysql, mbstring #Ajoute les extensions nécessaires
          tools: composer #Installe composer

      - name: Installation des dépendances Composer
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Lint PHP files
        run: find . -type f -name "*.php" ! -path "./vendor/*" -exec php -l {} \; | grep "No syntax errors detected"

      - name: Exécution des tests PHPUnit
        run: vendor/bin/phpunit #Assurez-vous que PHPUnit est configuré
